/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa;

/**
 *
 * @author Julian
 */
public class EstadoActualCaja extends javax.swing.JFrame {

    /**
     * Creates new form EstadoActualCaja
     */
    public EstadoActualCaja() {
        initComponents();
       // EstadoCaja.setText(estado);
        Conexion manager = new Conexion();
        String queryProveedores = "select cedula, tipo, nombre, apellido1, apellido2, descuento, contacto, email from persona natural join proveedor;";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CantidadEnCaja = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonAbrirCaja = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        EstadoCaja = new javax.swing.JLabel();
        ButtonCerrarCaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("La caja tiene en este momento ");

        CantidadEnCaja.setText("0");

        jLabel3.setText("colones");

        ButtonAbrirCaja.setText("Abrir Caja");
        ButtonAbrirCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAbrirCajaActionPerformed(evt);
            }
        });

        jLabel4.setText("La caja esta");

        EstadoCaja.setText("CERRADA");

        ButtonCerrarCaja.setText("Cerrar Caja");
        ButtonCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(EstadoCaja))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonAbrirCaja)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CantidadEnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(ButtonCerrarCaja))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CantidadEnCaja)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EstadoCaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAbrirCaja)
                    .addComponent(ButtonCerrarCaja))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAbrirCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAbrirCajaActionPerformed
        EstadoCaja.setText("Abierta");
        this.setVisible(false);
    }//GEN-LAST:event_ButtonAbrirCajaActionPerformed

    private void ButtonCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCerrarCajaActionPerformed
        EstadoCaja.setText("Cerrada");
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCerrarCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAbrirCaja;
    private javax.swing.JButton ButtonCerrarCaja;
    private javax.swing.JLabel CantidadEnCaja;
    private javax.swing.JLabel EstadoCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
