/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa;

/**
 *
 * @author Julian
 */
public class ViewAdminSucursalSolicitarProductos extends javax.swing.JFrame {

    /**
     * Creates new form ViewAdminSucursalSolicitarProductos
     */
    public ViewAdminSucursalSolicitarProductos(String cedula) {
        initComponents();
        LabelProductosFacturados.setVisible(false);
        ButtonModificar.setVisible(false);
        ButtonEliminar.setVisible(false);
        LabelNumCedula.setVisible(false);
        LabelNumCedula.setText(cedula);
        
        Conexion manager = new Conexion();
        
        String queryInventario = "select cod, descripcion, minimo, existencia, medida, costo, precio1, precio2, precio3 from producto order by cod ASC;";
        manager.llenarTabla(queryInventario, TableInventario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonCancelar = new javax.swing.JButton();
        LabelCodBarras = new javax.swing.JLabel();
        LabelDescripcion = new javax.swing.JLabel();
        TextFieldCodBarras = new javax.swing.JTextField();
        TextFieldDescripcion = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        ScrollPaneBuscar = new javax.swing.JScrollPane();
        TableInventario = new javax.swing.JTable();
        LabelCodBarras1 = new javax.swing.JLabel();
        TextFieldCodBarrasAgregar = new javax.swing.JTextField();
        LabelCantidad = new javax.swing.JLabel();
        TextFieldCantidad = new javax.swing.JTextField();
        ButtonAgregar = new javax.swing.JButton();
        ScrollPaneBuscar1 = new javax.swing.JScrollPane();
        TablePedido = new javax.swing.JTable();
        ButtonModificar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        LabelNumCedula = new javax.swing.JLabel();
        LabelProductosFacturados = new javax.swing.JLabel();
        ButtonEnviarSolicitud = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        LabelCodBarras.setText("Codigo Barras");

        LabelDescripcion.setText("Descripcion");

        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        TableInventario.setAutoCreateRowSorter(true);
        TableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cant. Min.", "Cant. Actual", "Medida", "Precio Costo", "Precio1", "Precio2", "Precio3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableInventario.getTableHeader().setReorderingAllowed(false);
        ScrollPaneBuscar.setViewportView(TableInventario);

        LabelCodBarras1.setText("Codigo Barras");

        LabelCantidad.setText("Cantidad");

        TextFieldCantidad.setText("1");

        ButtonAgregar.setText("Agregar");
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });

        TablePedido.setAutoCreateRowSorter(true);
        TablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePedido.getTableHeader().setReorderingAllowed(false);
        ScrollPaneBuscar1.setViewportView(TablePedido);

        ButtonModificar.setText("Modificar");

        ButtonEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonCancelar))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPaneBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCodBarras)
                                    .addComponent(LabelDescripcion))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelNumCedula)
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelProductosFacturados))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(LabelCodBarras1)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldCodBarrasAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ScrollPaneBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodBarras)
                    .addComponent(TextFieldCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDescripcion)
                    .addComponent(TextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar)
                    .addComponent(LabelNumCedula)
                    .addComponent(LabelProductosFacturados))
                .addGap(44, 44, 44)
                .addComponent(ScrollPaneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodBarras1)
                    .addComponent(TextFieldCodBarrasAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCantidad)
                    .addComponent(TextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneBuscar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEliminar)
                        .addGap(64, 64, 64))))
        );

        ButtonEnviarSolicitud.setText("Enviar Solicitud");
        ButtonEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarSolicitudActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        LabelTotal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonEnviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(731, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(LabelTotal)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonEnviarSolicitud)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
       
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarSolicitudActionPerformed
        String cedulaCajero = LabelNumCedula.getText();
        //String total = LabelValueTotal.getText();
        String num_caja = "1";
        String total = LabelTotal.getText();
        int num_rows = (int) TablePedido.getRowCount();
        
        Conexion manager = new Conexion();
        String insertFactura = "insert into Compra values(default, '"+cedulaCajero+"', "+total+", CURRENT_TIMESTAMP) returning ID_Solicitud;";
        manager.consulta(insertFactura);
        String ID_Solicitud = manager.getHileraResultado();
        ID_Solicitud = ID_Solicitud.replaceAll("\\W","");
        //System.out.print("paso 1");
        
        for(int i=0;i<num_rows;i++){
            //inserto cada producto en facturados
            Conexion manager2 = new Conexion();
            String codigo = TablePedido.getValueAt(i,0).toString();
            int cantidad = Integer.parseInt( TablePedido.getValueAt(i,2).toString() );
            double precio = Double.parseDouble( TablePedido.getValueAt(i,3).toString() );
            String proveedor = "-1"; //siempre deben hacer solicitudes a sucursal principal
            
            
            String insertFacturado = "insert into solicitud values("+ID_Solicitud+", '"+codigo+"', '"+cedulaCajero+"', '"+proveedor+"',  "+cantidad+", "+precio+");";
            manager2.consulta(insertFacturado);
            
        }
        this.dispose();
    }//GEN-LAST:event_ButtonEnviarSolicitudActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        String codigo = TextFieldCodBarras.getText();
        String descripcion = TextFieldDescripcion.getText();
        String selectInventario = "";
        if(descripcion.equals("")){
            selectInventario = "select cod, descripcion, minimo, existencia, medida, costo, precio1, precio2, precio3 from producto where cod='"+codigo+"';";
        }else{
            selectInventario = "select cod, descripcion, minimo, existencia, medida, costo, precio1, precio2, precio3 from producto where cod='"+codigo+"' or descripcion like '%"+descripcion+"%' ;";
        }
        
        Conexion manager = new Conexion();
        manager.llenarTabla(selectInventario, TableInventario);
    }//GEN-LAST:event_ButtonBuscarActionPerformed
    private void Refresh(){
        Conexion manager = new Conexion();
        String queryInventario = "select cod, descripcion, minimo, existencia, medida, costo, precio1, precio2, precio3 from producto order by cod ASC;";
        manager.llenarTabla(queryInventario, TableInventario);
        
        String ProductosFacturados = LabelProductosFacturados.getText();
        String query = "select * from ("+ProductosFacturados+") as A;"; //ejecuta el nuevo query
        manager.llenarTabla(query, TablePedido);
        
        
        int num_rows = (int) TablePedido.getRowCount();
        double subtotal = 0.0;
        for(int i=0;i<num_rows;i++){
            int cantidad= Integer.parseInt( TablePedido.getValueAt(i,2).toString() );
            double valor = Double.parseDouble( TablePedido.getValueAt(i,3).toString() );
            subtotal = subtotal + cantidad* (int) valor;
        }
        LabelTotal.setText( Double.toString(subtotal));
    }
    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        int row = TableInventario.getSelectedRow();
        int column = 0;
        String codigo = TextFieldCodBarrasAgregar.getText();
        String cantidad = TextFieldCantidad.getText();
        
        if((TextFieldCodBarrasAgregar.getText()).equals("")){
            codigo = TableInventario.getValueAt(row, column).toString();
        }
        
        
        
        Conexion manager = new Conexion();
        
        String ProductosFacturados = LabelProductosFacturados.getText();
   
        if( ProductosFacturados.contains("select") ){ //si ya hay productos facturados agrega un union
            ProductosFacturados = ProductosFacturados+" UNION ";
        }
        String queryProducto = "select cod as Codigo, descripcion as Descripcion, '"+cantidad+"' as Cantidad, costo as Precio from producto where cod='"+codigo+"'"; //query de nuevo producto
        ProductosFacturados = ProductosFacturados+queryProducto; //agregar query de nuevo producto
        LabelProductosFacturados.setText(ProductosFacturados); //almacena nuevo query
        String query = "select * from ("+ProductosFacturados+") as A;"; //ejecuta el nuevo query
        
        manager.llenarTabla(query, TablePedido);
        this.Refresh();
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonEnviarSolicitud;
    private javax.swing.JButton ButtonModificar;
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelCodBarras;
    private javax.swing.JLabel LabelCodBarras1;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelNumCedula;
    private javax.swing.JLabel LabelProductosFacturados;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JScrollPane ScrollPaneBuscar;
    private javax.swing.JScrollPane ScrollPaneBuscar1;
    private javax.swing.JTable TableInventario;
    private javax.swing.JTable TablePedido;
    private javax.swing.JTextField TextFieldCantidad;
    private javax.swing.JTextField TextFieldCodBarras;
    private javax.swing.JTextField TextFieldCodBarrasAgregar;
    private javax.swing.JTextField TextFieldDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
